# Generated by Django 4.2 on 2023-04-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oneEl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="own",
            name="modelgaika",
            field=models.IntegerField(default=0),
        ),
    ]
